### PR TITLE
Quiz Put Route

### LINKED ISSUE #57: Add PUT route to api quiz end point.
The api end point /api/v1/quiz needs a PUT route added to the router with associated router handler. 

Route should accept a quiz object and replace the quiz data in database with the matching id.

Quiz data in database is separated into three tables: quiz, question, answer.  Each row relating to the quiz data for each table will need to be adjusted based on the quiz object properties send to the PUT route.

Untitled

### PR DESCRIPTION
**Pull request by dpajek**
about: Added route, controller, and update sql for updating a quiz
assignees: 'dpajek'

Resolves #57

Note: I had to bypass verification during commit `--no-verify` Otherwise, I was getting errors related to the pageheader that were stopping me from committing. I don't think they're relevant to this PR: 

```
× eslint **/*.js --fix-dry-run:
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.     

  17:10  error  PageHeader not found in '../../components/shared/styles'           import/named
  18:20  error  Unable to resolve path to module '../../components/header/Header'  import/no-unresolved
  18:20  error  Missing file extension for "../../components/header/Header"        import/extensions
  22:32  error  Unable to resolve path to module '../../components/footer/styles'  import/no-unresolved

✖ 5 problems (5 errors, 0 warnings)

husky > pre-commit hook failed (add --no-verify to bypass)
```

### CODE REVIEW

**Comment by dpajek** [comment]
@silentkdev

**Review by silentkdev — CHANGES_REQUESTED** [review]
I'm thinking we should put in a check for the length of the array for `verifySubject` (line 58) and `verifyTag` (line 73) like we do with `verifyQuiz` (line 44) in `/server/controllers/apiV1/quiz/put.js`

**Comment by silentkdev** [comment]
I didn't even realize that I missed those on the POST request great catch!  Thanks for the changes. @dpajek

**Comment by dpajek** [comment]
@silentkdev done. I also added it to the post request.

Oddly, the selectQuizById would return [] if it found nothing and, without the length check, it wouldn't error out.
selectSubjectById would fail, so it didn't seem to need the length check. In any case, it does seem better for them to be more consistent.

**Review by silentkdev — APPROVED** [review]

**Comment by silentkdev** [comment]
@dpajek ah okay that totally makes sense then.

**Review by cMikolai — APPROVED** [review]
Cool, thanks!

**Pull request merged**
