### PR TITLE
Feature/184 insert new role function

### LINKED ISSUE #184: Create and test a function `insertNewRole`
This issue requires that #181 is resolved first.

We need a function to insert a new role into the roles table in the DB.

The functions should take this shape:
```ts
const insertNewRole = async (name: string) => {
  // Have fun
}
```

Return either the result of the insert query or `null` for when the role already exists.

- Function should be in `db/roles.ts`
- Also write tests to test in `test/roles.test.ts`

### PR DESCRIPTION
**Pull request by ZumDeWald**
---
about: This PR adds `insertNewRole` DB function and related tests
---

Details:
- Added function `insertNewRole` to insert a role into the roles table
- Added tests to verify and made sure they are passing

Resolves #184

### CODE REVIEW

**Review by jaytula — CHANGES_REQUESTED** [review]
Looks good! Just a small TypeScript suggestion so that `insertNewRole` is more type-aware of what it returns. Slightly restructure the function like this:

```ts
export async function insertNewRole(name: string) {
  const client = await getConnection();

  const matchRows = await client.query(
    `SELECT FROM ONLY roles WHERE roleName = $1`,
    [name]
  );

  if (matchRows.rowCount !== 0) return null;

  return client.query(
    `
        INSERT INTO roles (roleId, roleName)
        VALUES (DEFAULT, $1)
      `,
    [name]
  );
}
```

**Comment by ZumDeWald** [comment]
> Looks good! Just a small TypeScript suggestion so that `insertNewRole` is more type-aware of what it returns. Slightly restructure the function like this:
> 
> ```ts
> export async function insertNewRole(name: string) {
>   const client = await getConnection();
> 
>   const matchRows = await client.query(
>     `SELECT FROM ONLY roles WHERE roleName = $1`,
>     [name]
>   );
> 
>   if (matchRows.rowCount !== 0) return null;
> 
>   return client.query(
>     `
>         INSERT INTO roles (roleId, roleName)
>         VALUES (DEFAULT, $1)
>       `,
>     [name]
>   );
> }
> ```

@jaytula  - Can do! I had it structured that way (check and return null before the insert) but changed it to match the form of similar functions in `users`.
I would prefer they all invert the if and try to return null first. Should I refactor the others to match while I'm changing this one?

**Comment by jaytula** [comment]
> > Looks good! Just a small TypeScript suggestion so that `insertNewRole` is more type-aware of what it returns. Slightly restructure the function like this:
> > ```ts
> > export async function insertNewRole(name: string) {
> >   const client = await getConnection();
> > 
> >   const matchRows = await client.query(
> >     `SELECT FROM ONLY roles WHERE roleName = $1`,
> >     [name]
> >   );
> > 
> >   if (matchRows.rowCount !== 0) return null;
> > 
> >   return client.query(
> >     `
> >         INSERT INTO roles (roleId, roleName)
> >         VALUES (DEFAULT, $1)
> >       `,
> >     [name]
> >   );
> > }
> > ```
> 
> @jaytula - Can do! I had it structured that way (check and return null before the insert) but changed it to match the form of similar functions in `users`. I would prefer they all invert the if and try to return null first. Should I refactor the others to match while I'm changing this one?

I'm okay either way. You can refactor the others now if you want or leave it for later.

**Review by jaytula — APPROVED** [review]
Looks good!

Note that you don't have to `await` a Promise with `return` statements in `async` functions.

**Review by jaytula — APPROVED** [review]

**Review by ghost — APPROVED** [review]
awesome work thanks again @ZumDeWald

**Pull request merged**
