### PR TITLE
Update the paragraph on the back-end (#154)

### LINKED ISSUE #154: Update copy on About Us page
**Story:**
As a user I expect the information on the about us to be up to date so that I am not confused by incorrect information.

**Details:**
- Info under `What are you using to build this app?` section needs updated (no longer using express, etc.)
- Review all other info and make sure it is up to date

### PR DESCRIPTION
**Pull request by jaytula**
I've updated the paragraph describing the back-end. It should more accurately describe the current state of the app but might be a bit excessive.

### CODE REVIEW

**Comment by ghost** [comment]
My vote is that we remove "backend" terminology from the repo.  It just confused people, we are actually working in the backend already because that's where next lives.  Next does indeed let you create an api if you need one but we don't need one so I don't expect we will ever create an api.

**Comment by silentkdev** [comment]
My vote is that we remove "backend" terminology from the repo.  It just confused people, we are actually working in the backend already because that's where next lives.  Next does indeed let you create an api if you need one but we don't need one so I don't expect we will ever create an api.

**Comment by jaytula** [comment]
@silentkdev My mistake, I presumed that we would eventually have one.  Should I remove the entire section on the *Backend* that was added here?

**Comment by ghost** [comment]
I think we should remove front-end and back-end verbage.  NextJS handles both sides of the stack so something more appropriate might be that it's a nextjs app powered by a postgres database or something along those lines.  Maybe link to the official nextjs and postgresql websites with a line about "for more info..."

**Comment by jaytula** [comment]
@silentkdev I've simplified per your comment: 3948ba7

**Review by ghost — APPROVED** [review]
Awesome thanks!

**Review by rmcguire6 — APPROVED** [review]
Looks good.

**Pull request merged**
